name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt install -y libglfw3-dev libsdl2-dev libopenal-dev libglvnd-core-dev iwyu clang-tidy clang-tools

    - name: Build OSP-Magnum
      run: |
        scan-build -o scanlogs cmake -B build -DCMAKE_BUILD_TYPE=Release
        scan-build -o scanlogs cmake --build build --parallel --config Release --target osp-magnum
